'use client';

import { FormEvent, useEffect, useState } from 'react';
import Image from 'next/image';
import QRCode from 'qrcode';
import { useNativeWallet } from '@/hooks/useNativeWallet';
import { buildAndSignXlmPayment, horizon } from '@/lib/stellar';

const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3101';
const headers = (): Record<string, string> => process.env.NEXT_PUBLIC_API_KEY ? { 'x-api-key': process.env.NEXT_PUBLIC_API_KEY } : {};
const short = (value: string) => `${value.slice(0, 6)}...${value.slice(-5)}`;

export function NativeWallet() {
  const wallet = useNativeWallet();
  const [mode, setMode] = useState<'home' | 'create' | 'import' | 'unlock' | 'backup' | 'dashboard' | 'receive' | 'send'>('home');
  const [password, setPassword] = useState('');
  const [confirm, setConfirm] = useState('');
  const [rawSecret, setRawSecret] = useState('');
  const [backupSecret, setBackupSecret] = useState<string | null>(null);
  const [balance, setBalance] = useState<string | null>(null);
  const [qr, setQr] = useState<string | null>(null);
  const [recipient, setRecipient] = useState('');
  const [amount, setAmount] = useState('');
  const [memo, setMemo] = useState('');
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<string | null>(null);

  useEffect(() => { if (wallet.ready && (mode === 'home' || mode === 'unlock')) setMode(wallet.encryptedWallet ? (wallet.isUnlocked ? 'dashboard' : 'unlock') : 'home'); if (wallet.ready && mode === 'dashboard' && !wallet.isUnlocked) setMode('unlock'); }, [wallet.ready, wallet.encryptedWallet, wallet.isUnlocked, mode]);
  useEffect(() => { if (!wallet.address) return; horizon.loadAccount(wallet.address).then((account) => setBalance(account.balances.find((item) => item.asset_type === 'native')?.balance ?? '0')).catch((error: unknown) => setMessage((error as { response?: { status?: number } })?.response?.status === 404 ? 'Account not activated on Stellar Testnet yet.' : 'Unable to load Testnet balance.')); }, [wallet.address]);
  useEffect(() => { if (wallet.address && mode === 'receive') QRCode.toDataURL(`stellar:${wallet.address}`).then(setQr).catch(() => setQr(null)); }, [wallet.address, mode]);

  async function submitWallet(event: FormEvent) {
    event.preventDefault(); setMessage(null);
    if (password !== confirm) return setMessage('Passwords do not match.');
    setBusy(true);
    try { const recoverySecret = mode === 'create' ? (await wallet.create(password)).secret : rawSecret.trim(); if (mode === 'import') await wallet.importWallet(rawSecret, password); setBackupSecret(recoverySecret); setMode('backup'); setPassword(''); setConfirm(''); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to save wallet locally.'); }
    finally { setBusy(false); }
  }
  async function unlock(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(null); try { await wallet.unlock(password); setPassword(''); setMode('dashboard'); } catch { setMessage('Incorrect wallet password or corrupted wallet data.'); } finally { setBusy(false); } }
  async function send(event: FormEvent) {
    event.preventDefault(); if (!wallet.secret) return setMessage('Unlock your wallet before signing.'); setBusy(true); setMessage('Building and signing locally...');
    try { const signedXdr = await buildAndSignXlmPayment(wallet.secret, recipient, amount, memo); const response = await fetch(`${apiUrl}/stellar/submit`, { method: 'POST', headers: { 'Content-Type': 'application/json', ...headers() }, body: JSON.stringify({ signedXdr, publicKey: wallet.address }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? 'Transaction submission failed'); setMessage(`Transaction submitted: ${result.hash}`); setRecipient(''); setAmount(''); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Transaction failed.'); } finally { setBusy(false); }
  }
  if (!wallet.ready) return <section className="rounded-lg border bg-white p-6">Loading wallet...</section>;
  if (mode === 'home') return <section className="rounded-lg border border-[#d9e8e2] bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#0a5c4a]">AfriPay Wallet</p><h2 className="mt-2 text-2xl font-bold text-[#102a2a]">Your Stellar wallet for payments.</h2><p className="mt-2 text-sm text-slate-600">No registration required. Your keys stay encrypted on this device.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><button onClick={() => setMode('create')} className="rounded-md bg-[var(--afripay-primary)] px-4 py-3 font-bold text-white">Create Wallet</button><button onClick={() => setMode('import')} className="rounded-md border border-[#0a5c4a] px-4 py-3 font-bold text-[#0a5c4a]">Import Wallet</button></div></section>;
  if (mode === 'backup') return <section className="rounded-lg border border-amber-300 bg-amber-50 p-6"><h2 className="text-xl font-bold text-amber-950">Back up your recovery secret</h2><p className="mt-2 text-sm text-amber-900">Write this down and store it offline. Never share it or put it in a screenshot. AfriPay cannot recover it.</p><code className="mt-4 block break-all rounded-md bg-white p-4 text-sm text-slate-900">{backupSecret}</code><label className="mt-4 flex gap-2 text-sm text-amber-950"><input type="checkbox" required /> I have securely backed up my recovery secret.</label><button onClick={() => { setBackupSecret(null); setRawSecret(''); setMode('dashboard'); }} className="mt-5 rounded-md bg-[#102a2a] px-4 py-3 font-bold text-white">Continue to wallet</button></section>;
  if (mode === 'unlock') return <form onSubmit={unlock} className="rounded-lg border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-[#102a2a]">Unlock Wallet</h2><p className="mt-2 text-sm text-slate-600">{wallet.encryptedWallet && short(wallet.encryptedWallet.publicKey)} · Stellar Testnet</p><input autoFocus required type="password" minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Wallet password" className="mt-5 w-full rounded-md border px-3 py-3" /><button disabled={busy} className="mt-4 w-full rounded-md bg-[var(--afripay-primary)] px-4 py-3 font-bold text-white">{busy ? 'Unlocking...' : 'Unlock Wallet'}</button>{message && <p role="alert" className="mt-3 text-sm text-red-700">{message}</p>}</form>;
  if (mode === 'create' || mode === 'import') return <form onSubmit={submitWallet} className="rounded-lg border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-[#102a2a]">{mode === 'create' ? 'Create Wallet' : 'Import Wallet'}</h2>{mode === 'import' && <textarea required value={rawSecret} onChange={(e) => setRawSecret(e.target.value)} placeholder="Enter your Stellar secret key (S...)" className="mt-5 min-h-24 w-full rounded-md border px-3 py-3 font-mono text-sm" />}{mode === 'create' && <p className="mt-3 text-sm text-slate-600">A new Stellar keypair will be generated locally in your browser.</p>}<input required type="password" minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Create password (8+ characters)" className="mt-4 w-full rounded-md border px-3 py-3" /><input required type="password" minLength={8} value={confirm} onChange={(e) => setConfirm(e.target.value)} placeholder="Confirm password" className="mt-3 w-full rounded-md border px-3 py-3" /><button disabled={busy} className="mt-4 w-full rounded-md bg-[var(--afripay-primary)] px-4 py-3 font-bold text-white">{busy ? 'Encrypting locally...' : 'Continue'}</button>{message && <p role="alert" className="mt-3 text-sm text-red-700">{message}</p>}</form>;
  if (mode === 'receive') return <section className="rounded-lg border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-[#102a2a]">Receive XLM</h2><p className="mt-2 break-all font-mono text-sm text-slate-600">{wallet.address}</p>{qr && <Image src={qr} alt="QR code for public Stellar address" width={224} height={224} className="mx-auto mt-5" />}<button onClick={() => navigator.clipboard.writeText(wallet.address ?? '')} className="mt-5 w-full rounded-md border px-4 py-3 font-bold text-[#0a5c4a]">Copy Address</button><button onClick={() => setMode('dashboard')} className="mt-3 w-full text-sm text-slate-500">Back</button></section>;
  if (mode === 'send') return <form onSubmit={send} className="rounded-lg border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-[#102a2a]">Send XLM · TESTNET</h2><input required value={recipient} onChange={(e) => setRecipient(e.target.value)} placeholder="Recipient G..." className="mt-5 w-full rounded-md border px-3 py-3 font-mono text-sm" /><input required inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="Amount" className="mt-3 w-full rounded-md border px-3 py-3" /><input value={memo} onChange={(e) => setMemo(e.target.value)} placeholder="Memo (optional)" className="mt-3 w-full rounded-md border px-3 py-3" /><p className="mt-4 text-xs text-slate-500">Review: {amount || '0'} XLM to {recipient ? short(recipient) : 'recipient'} on Testnet. Signing happens locally.</p><button disabled={busy} className="mt-4 w-full rounded-md bg-[var(--afripay-primary)] px-4 py-3 font-bold text-white">{busy ? 'Submitting...' : 'Sign & Send'}</button><p className="mt-3 text-xs text-slate-500">Network fee: 0.00001 XLM</p>{message && <p role="status" className="mt-3 break-all text-sm text-slate-700">{message}</p>}<button type="button" onClick={() => setMode('dashboard')} className="mt-3 w-full text-sm text-slate-500">Back</button></form>;
  return <section className="rounded-lg border bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#0a5c4a]">AfriPay Wallet · TESTNET</p><h2 className="mt-2 text-3xl font-bold text-[#102a2a]">{balance ?? '—'} XLM</h2><p className="mt-1 text-sm text-slate-500">{wallet.address && short(wallet.address)} · {balance === null ? 'Loading balance...' : 'Account balance'}</p></div><button onClick={wallet.lock} className="rounded-md border px-3 py-2 text-sm font-semibold">Lock</button></div><div className="mt-6 grid grid-cols-2 gap-3"><button onClick={() => setMode('send')} className="rounded-md bg-[var(--afripay-primary)] px-4 py-3 font-bold text-white">Send</button><button onClick={() => setMode('receive')} className="rounded-md border border-[#0a5c4a] px-4 py-3 font-bold text-[#0a5c4a]">Receive</button></div><div className="mt-6 rounded-md bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Wallet address</p><p className="mt-2 break-all font-mono text-sm text-slate-700">{wallet.address}</p><button onClick={() => navigator.clipboard.writeText(wallet.address ?? '')} className="mt-3 text-sm font-bold text-[#0a5c4a]">Copy Address</button></div><button onClick={() => { if (window.confirm('Remove this encrypted wallet from this device? Verify your backup first.')) wallet.remove(); }} className="mt-5 text-xs text-red-700 underline">Remove wallet from device</button>{message && <p role="status" className="mt-3 text-sm text-slate-600">{message}</p>}</section>;
}
